version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
#    network_mode: "host"
#    networks:
#      - my_network

  bot:
    build: .
    container_name: telegram_bot
    command: ["python3", "main.py"]
#    network_mode: "host"
    depends_on:
      - mongodb
#    environment:
#      - MONGO_URI=mongodb://mongodb:27017/tt_downloader
#    networks:
#      - my_network
    env_file:
      - .env

volumes:
  mongo_data:

#networks:
#  my_network: