version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  tor:
    image: torproject/tor
    container_name: tor_container
    ports:
      - "9050:9050"

  bot:
    build: .
    container_name: telegram_bot
    command: ["python3", "main.py"]
    depends_on:
      - mongodb
      - tor
    env_file:
      - .env

volumes:
  mongo_data:
