version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    container_name: telegram_bot
    command: ["python3", "main.py"]
    depends_on:
      - mongodb
    env_file:
      - .env
    network_mode: "host"  # Добавьте эту строку
