version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tt_downloader
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network: